/* twine-user-script #17: "definePlayer.js" */
variables().player = {
	name: "Jesse",
	sophieName: "",
	surname: "Doe",
	s: "SISSY",
	b: "BIMBO",
	d: "DEFAULT",
	wakeup: "room",
	MaxOP: 100,
	CurOP: 10,
	outfit: "casual1", outfits: [],
	hat: "none", hats: ["none"],
	underwear: "boxers1", underwears: ["none"],
	bra: "none", bras: ["none"],
	accf: "none", accfs: ["none"],
	accb: "none", accbs: ["none"],
	style: "you",
	penisSize: 0,
	pussySize: 0,
	breastSize: 0,
	assSize: 0,
	dose: 0,
	doseCD: 0,
	dayEventCD: 0,
	johnEventCD: 0,
	hairCD: -1,
	horny: 0,
	hornyMod: 0,
	dom: 50,
	genderv: 0,
	hLength: "Bald",
	hDesc: "completely shaved off",
	tfRate: 1,
	tfCD: 0,
	tfForever: 15,
	tfMale: 0,
	tfFemale: 0,
	tfTrans: 0,
	tfBimbo: 0,
	tfSissy: 0,
	daysMale: 0,
	daysFemale: 0,
	daysSissy: 0,
	daysTrans: 0,
	daysBimbo: 0,
	makeup: 0,
	wearingMakeup: ["no","@@.tf;light@@","@@.xxx;heavy@@"],
	makeupLevel: ["None","Light Makeup","Slutty Makeup"],
	coinOutfits: ["default"],
	wolf: 0,
	ram: 0,
	hart: 0,
	baseGender: "male",
	
};

variables().player.pref = {
	kiss: {give: variables().LIKE, get: variables().LIKE},
	analFuck: {give: variables().LIKE, get: variables().LIKE},
	pussyFuck: {give: variables().LOVE, get: variables().NEUTRAL},
	analPlay: {give: variables().LIKE, get: variables().LIKE},
	pussyPlay: {give: variables().NEUTRAL, get: variables().NEUTRAL},
	rimjob: {give: variables().NEUTRAL, get: variables().NEUTRAL},
	eatPussy: {give: variables().LIKE, get: variables().LOVE},
	suckCock: {give: variables().LIKE, get: variables().LOVE},
	gangbang: {give: variables().NEUTRAL, get: variables().NEUTRAL},
	cock: {have: variables().NEUTRAL, want: variables().NEUTRAL},
	pussy: {have: variables().NEUTRAL, want: variables().NEUTRAL},
	breasts: {have: variables().NEUTRAL, want: variables().NEUTRAL},
	bigBreasts: {have: variables().NEUTRAL, want: variables().NEUTRAL},
	smallBreasts: {have: variables().NEUTRAL, want: variables().NEUTRAL},
	sex: {men: variables().NEUTRAL, women: variables().NEUTRAL, trans: variables().NEUTRAL, family: variables().NEUTRAL}
};

variables().player.flag = {};
variables().player.has = {};
variables().player.control = {};
variables().player.met = {};
variables().player.tracking = {};